{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"An error occurred while saving the entity changes. See the inner exception for details.\n42P01: relation \"Users\" does not exist\n\nPOSITION: 13","children":[{"name":"AuthE2ETests.AuthAndChangePassword_FullFlow_WorksCorrectly","uid":"35897ee6249dec08","parentUid":"5c72738a6331e11fd658e3b9dab259e0","status":"broken","time":{"start":1761597925914,"stop":1761597927649,"duration":1735},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"5c72738a6331e11fd658e3b9dab259e0"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}